import "./base.css";
import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Noto_Sans_SC, Open_Sans, Fira_Code } from "next/font/google";
import clsx from "clsx";
import "./app.css";

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans-sc",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode;
  }>
) {
  const { children } = props;

  return (
    <html
      lang="zh-CN"
      suppressHydrationWarning
      className={clsx(
        openSans.variable,
        notoSansSC.variable,
        firaCode.variable
      )}
    >
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
