import "./base.css";
import type { Metadata } from "next";
import { Noto_Sans_SC, Open_Sans, Fira_Code } from "next/font/google";
import clsx from "clsx";
import "./app.css";
import { ThemeProvider } from "@/components/theme-provider";
import { PropsWithChildren } from "react";

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans-sc",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html
      lang="zh-CN"
      suppressHydrationWarning
      className={clsx(
        openSans.variable,
        notoSansSC.variable,
        firaCode.variable,
      )}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
